# Generated by Django 4.2.5 on 2023-10-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
