# Generated by Django 4.2.5 on 2023-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='valor',
            field=models.BooleanField(default=False),
        ),
    ]
