# Generated by Django 4.2.5 on 2023-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='author',
        ),
        migrations.AddField(
            model_name='attendance',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
